[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
baseSepolia = "https://sepolia.base.org"
optimismSepolia = "https://sepolia.optimism.io"

[etherscan]
baseSepolia = { key = "837IE7VQ7VADIRAN139YC9ZG8ID8UFJR2F" }
optimismSepolia = { key = "F49JQVIC5YDE15NHF55RMH31HNCV8BPIA4" }

[fmt]
multiline_func_header = "params_first"
line_length = 80
tab_width = 2
quote_style = "double"
bracket_spacing = true
int_types = "long"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
